-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgeZ+nOD8sdmu2VKbE
4XbrsNAqyOxVcnC1UsNzfvlD+kugCgYIKoZIzj0DAQehRANCAATlTlOwMpyBDKRD
2C4wKPNqW9EuEflZgvIxijqz8iuyIMZw89zsd2Qj88Il1LziWyeM8BKww0ja3BWN
TZHkoLY3
-----END PRIVATE KEY-----